disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Christopher Lyons"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
author = { name = "Chris Lyons", image = "logo2.png", headline = "Welcome to my personal website! Click on the Services link to learn more about what I do and to request an estimate."}

[author]
links = [ { email = "chrislyons.create@gmail.com" }, { instagram = "https://www.instagram.com/bigfootdood/" }, { linkedin = "https://www.linkedin.com/in/christopher-lyons-a33a1195/" } ]
