baseURL = 'https://chrislyons.tech/'
languageCode = 'en-us'
title = 'Chris Lyons'
theme = 'risotto'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

      
[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 10

    [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10


[params.theme]
palette = "dracula"

[params.about]
title = "ChrisLyons.net"
description = "We're all in this together."

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:chrislyons.create@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-instagram"
title = "Insta"
url = "https://www.instagram.com/bigfootdood/"