baseURL = 'https://chrislyons.tech/'
languageCode = 'en-us'
title = 'Chris Lyons'
theme = 'risotto'


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

    [[menu.main]]
    identifier = "services"
    name = "Services"
    url = "/services/"
    weight = 10

    [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10


[params.theme]
palette = "tender"